### ISSUE TITLE
QA Issues 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#115]
https://docs.google.com/document/d/1VnL7Zsgauct_MNW3BzcuFmVzKIMnTtIq2S4WmlDPcko/edit?usp=sharing

**Comment by prince-cedcoss** [comment]
@Sukirti-CEDCOSS  i have fixed the concern mentioned above, but there are some which are intentionally written,
1.domain name of pro plugin is written in org , as some code of pro is used in org that's why we used the pro plugin domain.
2.Woocommerce domain is written as we used the woocommerce api and tab .

**Comment by Sukirti-CEDCOSS** [comment]
verified
